public enum TokenType
{
  // Single-character Tokens
  LEFT_PARENTESIS, RIGHT_PARENTESIS,

  MUL, COMMA, CONCAT, MINUS, DOT, PLUS, POWER, SEMICOLON, DIV,

  // Comparison Tokens
  NOT, NOT_EQUAL, EQUAL, EQUAL_EQUAL, GREATER, GREATER_EQUAL, LESS, LESS_EQUAL, IMPLIES,

  // Literals
  BOOLEAN, STRING, NUMBER, IDENTIFIER,

  // Keywords
  AND, ELSE, FALSE, FOR, FUNCTION, IF, LET, IN, OR, PRINT, RETURN, TRUE, WHILE,

  EOF
}